### ISSUE TITLE
トップやコンテンツページの画像を用意する

### ISSUE THREAD

**Issue by kyonya** [kyonya/cc-portal#21]
C&Cにあった画像を用意、写真を撮るなど。
例：珈琲の焙煎画像など

**Comment by gennei** [comment]
珈琲西武で撮影するのも1つの手かな。

**Comment by kyonya** [comment]
トップの画像は終わり。
イベントページの画像だけど、データベースの変更、お願いしてもいいかな。
http://saradnentika.net/cc/events_image09.png
http://saradnentika.net/cc/events_image10.png
http://saradnentika.net/cc/events_image11.png
http://saradnentika.net/cc/events_image12.png

**Comment by kyonya** [comment]
ブラッシュアップしたい気もするけど、必要があれば別途issueを立てる。

**Comment by gennei** [comment]
https://github.com/kyonya/cc-portal/issues/21#issuecomment-200386770

close して問題ないよね？

**Comment by kyonya** [comment]
OK!
